### ISSUE TITLE
Rename `me` to `nab`. It's short and means "catch"

### ISSUE THREAD

**Issue by rrmckinley** [amio-io/await-trace#2]
The name `me` (shortened from `catchMe`) is a little distant from the intent. `nab` is only one letter longer and it is the shortest word that means "catch".

https://www.google.com/search?q=define+nab

**Comment by zatziky** [comment]
@rrmckinley Hey McKinley, thank you for PR! I myself don't mind it but I would like to hear an opinion of other people. Any idea - @ak1394 @capaj @lpgera @FranckFreiburger @Alexsey

If we change it to `nab`, then it will break the code of other developers. Then we should increase the version to `2.0.0`.

I will leave it open for 1 week. Upon opinions (if any will appear) we will see whether to merge or not. Hope you're fine with it. ;)

**Comment by rrmckinley** [comment]
> If we change it to nab, then it will break the code of other developers

The way I wrote [PR 3](https://github.com/amio-io/await-trace/pull/3), it keeps `me` in the exports and adds `nab`. `catchMe` was not named in the exports. Would any developers be depending on `catchMe` by name?

**Comment by Alexsey** [comment]
IMHO `nab` is better than `me`. But in any case, I think the right way for this package is to become a Babel plugin. And as for Babel plugin, the var name is not so important

**Comment by zatziky** [comment]
@rrmckinley Thank you for the improvement! It's merged and published to npm.
